site_name: Ideascube
pages:
- Home: index.md
- Installation: install.md
- Configuration: config.md
- Contributing: contributing.md
- Translations: i18n.md
- Make a Release: release_process.md
theme: yeti
repo_url: https://github.com/ideascube/ideascube
site_description: Ideas Box server core application.
